apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-journal-app
  namespace: var10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-journal-app
  template:
    metadata:
      labels:
        app: school-journal-app
    spec:
      hostAliases:
      - ip: "10.60.3.27"
        hostnames:
        - "hl22.zil"
      - ip: "10.60.3.28"
        hostnames:
        - "hl23.zil"
      containers:
      - name: school-journal-app
        image: izrafil/school-journal-app:17
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
      imagePullSecrets:
      - name: dockerhub-secret
