apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: school-journal-app-hpa
  namespace: var10
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: school-journal-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Масштабировать, если CPU > 50% от request (т.е. > 0.5 CPU)
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20  # Ждать 20 секунд устойчивой нагрузки перед масштабированием
      policies:
      - type: Percent
        value: 50  # Увеличивать на 50% текущего количества Pod (например, 1 → 2)
        periodSeconds: 20
      - type: Pods
        value: 1   # Но не менее 1 Pod за раз
        periodSeconds: 20
    scaleDown:
      stabilizationWindowSeconds: 30  # Ждать 60 секунд перед уменьшением реплик
      policies:
      - type: Percent
        value: 50  # Уменьшать на 50%
      - type: Pods
        value: 1   # Но не менее 1 Pod за раз