apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: school-journal-app-hpa
  namespace: var10
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: school-journal-app
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20  
      policies:
      - type: Pods
        value: 1   
        periodSeconds: 20
    scaleDown:
      policies:
      - type: Pods
        value: 1   
        periodSeconds: 20