apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: var10
spec:
  containers:
  - name: busybox
    image: busybox:1.35
    command: ['sh', '-c', 'echo "BusyBox is ready!" && sleep 3600']
    imagePullPolicy: IfNotPresent
  restartPolicy: Always