apiVersion: v1
kind: Service
metadata:
  name: school-journal-app
  namespace: var10
spec:
  selector:
    app: school-journal-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: calculation-service
  namespace: school-journal
spec:
  selector:
    app: calculation-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081