apiVersion: v1
kind: Service
metadata:
  name: school-journal-app-nodeport
  namespace: var10
spec:
  type: NodePort
  selector:
    app: school-journal-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080

---
apiVersion: v1
kind: Service
metadata:
  name: calculation-service-nodeport
  namespace: school-journal
spec:
  type: NodePort
  selector:
    app: calculation-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081