apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: var10
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=

---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: school-journal
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFYcHlZV1pwYkRwa1kydHlYM0JoZEY5MlpETk1VWFZwWkRsdVRXZHJNbTU0UkdjemQyNVNZamQxV0ZVPSIKCQl9Cgl9Cn0=